services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        FRONT_PORT: ${FRONT_PORT}
    image: psy2bib-frontend:latest
    container_name: psy2bib-frontend
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    environment:
      - FRONT_PORT=${FRONT_PORT}
    networks:
      - psy2bib-front-net

networks:
  psy2bib-front-net:
    driver: bridge
